name: Deploy

on:
 push:
  branches:
    - master

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository master branch
      uses: actions/checkout@master

    - name: Setup Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 16

    - name: Setup Hexo Dependencies
      run: |
        cd ./src
        npm install hexo-cli -g
        npm install

    - name: Setup Deploy Private Key
      env:
        HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Setup Git Infomation
      run: |
        git --version
        git config --global user.name 'action@github.com' 
        git config --global user.email 'GitHub Action'
    - name: Deploy Hexo
      run: |
        cd ./src
        hexo clean
        hexo generate 
        hexo deploy
